// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ianspire/amazing-payments/proto/payment.proto

package payment

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Customer method message group
type Customer struct {
	CustomerID           int64    `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	StripeCustomerKey    string   `protobuf:"bytes,4,opt,name=stripe_customer_key,json=stripeCustomerKey,proto3" json:"stripe_customer_key,omitempty"`
	StripeChargeDate     string   `protobuf:"bytes,5,opt,name=stripe_charge_date,json=stripeChargeDate,proto3" json:"stripe_charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetCustomerID() int64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Customer) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Customer) GetStripeCustomerKey() string {
	if m != nil {
		return m.StripeCustomerKey
	}
	return ""
}

func (m *Customer) GetStripeChargeDate() string {
	if m != nil {
		return m.StripeChargeDate
	}
	return ""
}

type CreateCustomerRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	StripeChargeDate     string   `protobuf:"bytes,3,opt,name=stripe_charge_date,json=stripeChargeDate,proto3" json:"stripe_charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{1}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateCustomerRequest) GetStripeChargeDate() string {
	if m != nil {
		return m.StripeChargeDate
	}
	return ""
}

type GetCustomerRequest struct {
	CustomerID           int64    `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	StripeCustomerKey    string   `protobuf:"bytes,4,opt,name=stripe_customer_key,json=stripeCustomerKey,proto3" json:"stripe_customer_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{2}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetCustomerID() int64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *GetCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetCustomerRequest) GetStripeCustomerKey() string {
	if m != nil {
		return m.StripeCustomerKey
	}
	return ""
}

type UpdateCustomerRequest struct {
	CustomerID           int64    `protobuf:"varint,1,opt,name=customerID,proto3" json:"customerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	StripeCustomerKey    string   `protobuf:"bytes,4,opt,name=stripe_customer_key,json=stripeCustomerKey,proto3" json:"stripe_customer_key,omitempty"`
	StripeChargeDate     string   `protobuf:"bytes,5,opt,name=stripe_charge_date,json=stripeChargeDate,proto3" json:"stripe_charge_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCustomerRequest) Reset()         { *m = UpdateCustomerRequest{} }
func (m *UpdateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCustomerRequest) ProtoMessage()    {}
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{3}
}

func (m *UpdateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCustomerRequest.Unmarshal(m, b)
}
func (m *UpdateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCustomerRequest.Merge(m, src)
}
func (m *UpdateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCustomerRequest.Size(m)
}
func (m *UpdateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCustomerRequest proto.InternalMessageInfo

func (m *UpdateCustomerRequest) GetCustomerID() int64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *UpdateCustomerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateCustomerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateCustomerRequest) GetStripeCustomerKey() string {
	if m != nil {
		return m.StripeCustomerKey
	}
	return ""
}

func (m *UpdateCustomerRequest) GetStripeChargeDate() string {
	if m != nil {
		return m.StripeChargeDate
	}
	return ""
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{4}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckResponse struct {
	IsHealthy            bool     `protobuf:"varint,1,opt,name=isHealthy,proto3" json:"isHealthy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_137163c83cdc169f, []int{5}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetIsHealthy() bool {
	if m != nil {
		return m.IsHealthy
	}
	return false
}

func init() {
	proto.RegisterType((*Customer)(nil), "payment.Customer")
	proto.RegisterType((*CreateCustomerRequest)(nil), "payment.CreateCustomerRequest")
	proto.RegisterType((*GetCustomerRequest)(nil), "payment.GetCustomerRequest")
	proto.RegisterType((*UpdateCustomerRequest)(nil), "payment.UpdateCustomerRequest")
	proto.RegisterType((*HealthCheckRequest)(nil), "payment.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "payment.HealthCheckResponse")
}

func init() {
	proto.RegisterFile("github.com/ianspire/amazing-payments/proto/payment.proto", fileDescriptor_137163c83cdc169f)
}

var fileDescriptor_137163c83cdc169f = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xd5, 0x3a, 0x2d, 0xb4, 0x53, 0x54, 0xc8, 0xb4, 0x15, 0x26, 0x8d, 0xaa, 0xe2, 0x53, 0x85,
	0xc0, 0x2b, 0xe8, 0x05, 0x71, 0x4d, 0x25, 0x40, 0x5c, 0x90, 0x11, 0x37, 0xa4, 0xb0, 0x75, 0x47,
	0xf6, 0x2a, 0xf1, 0xae, 0xf1, 0x6e, 0x22, 0x19, 0xc4, 0x85, 0x0f, 0xe0, 0xc2, 0x9f, 0xc0, 0x07,
	0xf0, 0x11, 0xfc, 0x02, 0x1f, 0x82, 0xb2, 0xb6, 0x13, 0x87, 0x98, 0x33, 0xea, 0x6d, 0x67, 0xde,
	0xdb, 0x79, 0xb3, 0x6f, 0xc6, 0x86, 0xa7, 0x89, 0xb4, 0xe9, 0xec, 0x32, 0x8c, 0x75, 0xc6, 0xa5,
	0x50, 0x26, 0x97, 0x05, 0x71, 0x91, 0x89, 0x8f, 0x52, 0x25, 0x8f, 0x72, 0x51, 0x66, 0xa4, 0xac,
	0xe1, 0x79, 0xa1, 0xad, 0xe6, 0x75, 0x18, 0xba, 0x08, 0x6f, 0xd6, 0xe1, 0x60, 0x98, 0x68, 0x9d,
	0x4c, 0x89, 0x8b, 0x5c, 0x72, 0xa1, 0x94, 0xb6, 0xc2, 0x4a, 0xad, 0x4c, 0x45, 0x0b, 0xbe, 0x33,
	0xd8, 0x19, 0xcd, 0x8c, 0xd5, 0x19, 0x15, 0x78, 0x02, 0x10, 0xd7, 0xe7, 0x97, 0x17, 0x3e, 0x3b,
	0x65, 0x67, 0xbd, 0xa8, 0x95, 0x41, 0x84, 0x2d, 0x25, 0x32, 0xf2, 0xbd, 0x53, 0x76, 0xb6, 0x1b,
	0xb9, 0x33, 0x1e, 0xc2, 0x36, 0x65, 0x42, 0x4e, 0xfd, 0x9e, 0x4b, 0x56, 0x01, 0x86, 0x70, 0x60,
	0x6c, 0x21, 0x73, 0x1a, 0x37, 0xd7, 0xc7, 0x13, 0x2a, 0xfd, 0x2d, 0xc7, 0xe9, 0x57, 0x50, 0x23,
	0xfb, 0x8a, 0x4a, 0x7c, 0x08, 0xd8, 0xf0, 0x53, 0x51, 0x24, 0x34, 0xbe, 0x12, 0x96, 0xfc, 0x6d,
	0x47, 0xbf, 0x53, 0xd3, 0x1d, 0x70, 0x21, 0x2c, 0x05, 0x1a, 0x8e, 0x46, 0x05, 0x09, 0xbb, 0x2c,
	0x11, 0xd1, 0x87, 0x19, 0x19, 0xbb, 0x6c, 0x90, 0x75, 0x35, 0xe8, 0xb5, 0x1b, 0xec, 0x16, 0xec,
	0xfd, 0x43, 0xf0, 0x2b, 0x03, 0x7c, 0x4e, 0xf6, 0x6f, 0xb9, 0xff, 0xe6, 0x57, 0xf0, 0x93, 0xc1,
	0xd1, 0xdb, 0xfc, 0xaa, 0xc3, 0x82, 0xeb, 0x32, 0xc3, 0x43, 0xc0, 0x17, 0x24, 0xa6, 0x36, 0x1d,
	0xa5, 0x14, 0x4f, 0xea, 0xee, 0x83, 0x73, 0x38, 0x58, 0xcb, 0x9a, 0x5c, 0x2b, 0x43, 0x38, 0x84,
	0x5d, 0x69, 0x2a, 0xa0, 0x74, 0x6f, 0xda, 0x89, 0x56, 0x89, 0x27, 0x3f, 0x3c, 0xd8, 0x7f, 0x5d,
	0x6d, 0xfb, 0x1b, 0x2a, 0xe6, 0x32, 0x26, 0x7c, 0x07, 0xfb, 0xeb, 0x1b, 0x82, 0x27, 0x61, 0xf3,
	0x7d, 0x74, 0xae, 0xce, 0xa0, 0xbf, 0xc2, 0x6b, 0x24, 0xb8, 0xfb, 0xe5, 0xd7, 0xef, 0x6f, 0x5e,
	0x3f, 0xb8, 0xc5, 0xe7, 0x8f, 0x79, 0xe3, 0xc1, 0x33, 0xf6, 0x00, 0xdf, 0xc3, 0x5e, 0x6b, 0x1b,
	0xf0, 0x78, 0x79, 0x75, 0x73, 0x47, 0xba, 0xea, 0xde, 0x77, 0x75, 0x8f, 0xf1, 0x5e, 0xbb, 0x2e,
	0xff, 0xb4, 0x1a, 0xd2, 0x67, 0x14, 0xb0, 0xd7, 0xf2, 0xa1, 0xa5, 0xb0, 0xe9, 0xd9, 0x60, 0xd8,
	0x0d, 0x56, 0xd6, 0x35, 0x8f, 0xc0, 0xdb, 0x0b, 0xb1, 0xd4, 0x11, 0xe2, 0x05, 0xe1, 0xf2, 0x86,
	0xfb, 0x01, 0x9c, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x11, 0x0a, 0xf2, 0x8b, 0x63, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PaymentServiceClient interface {
	// Customer Methods
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*Customer, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*Customer, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type paymentServiceClient struct {
	cc *grpc.ClientConn
}

func NewPaymentServiceClient(cc *grpc.ClientConn) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*Customer, error) {
	out := new(Customer)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/payment.PaymentService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
type PaymentServiceServer interface {
	// Customer Methods
	CreateCustomer(context.Context, *CreateCustomerRequest) (*Customer, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*Customer, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
}

func RegisterPaymentServiceServer(s *grpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&_PaymentService_serviceDesc, srv)
}

func _PaymentService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/payment.PaymentService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PaymentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _PaymentService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _PaymentService_GetCustomer_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PaymentService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/ianspire/amazing-payments/proto/payment.proto",
}
